---
- name: Wait for ssh connection
  host: docker_server
  gather_facts: False
  tasks:
    - name: Ensure ssh port open
      wair_for: 
        port: 22
        delay: 10
        timeout: 100
        search_regex: OpenSSH
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
       vars: 
        ansible_connection: local
        ansible_python_interpreter: /usr/bin/python
 
- name: Install python3, docker and docker-compose
  hosts: docker_server
  become: yes
  gather_facts: False # Avoiding error message by the interpreter for a new server using python3 instead of 2.
  tasks:
    - name: Install python3, docker
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name:
          - python3
          - docker
        update_cache: yes
        state: present
    - name: Install docker-compose
      get_url: "https://github.com/docker/compose/releases/download/2.18.1/docker-compose-Linux-{{ ansible_architecture }}"
      dest: /usr/local/bin/docker-compose
      mode: +x
    - name: Install docker python module
      pip:
        name: docker

- name: Start docker
  hosts: docker_server
  become: yes
  tasks:
    - name: Start docker daemon
      systemd:
        name: docker
        state: started
    - name: Install docker and docker-compose python module
      pip:
        name:
          - docker
          - docker-compose

- name: Add ec2-user to docker group
  hosts: docker_server
  become: yes
  tasks:
    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
    - name: Reconnect to server
      meta: reset_connection

- name: Start docker container
  hosts: docker_server
  vars_prompt: # You can use vars file to set up your password but it less secure.
    - name: docker_password
      prompt: Enter password for docker registry
  tasks:
    - name: Copy docker-compose
      copy:
        src: "{{ file_location }}"
        dest: "{{ home_destination }}"
    - name: Docker login
      docker_login:
        registry_url: https://index.docker.io/v1
        username: liory97
        password: "{{ docker_password }}"
    - name: Start containers from docker-compose
      docker-compose:
        project_src: "{{ home_destination }}"
        state: present
